# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "DiscoStarslayer's Starship NOP"
tagline:          "Darren's personal blog"
description:      'Star Slaying and Bee Gees'
url:              https://dtho.mp
baseurl:          /

author:
  name:           'Darren Thompson'
  url:            https://twitter.com/DiscoStarslayer

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DiscoStarslayer/blog

plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
