# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Starship NOP"
tagline:          "Darren's personal blog"
description:      "Star Slaying and Bee Gees"
url:              https://blog.dtho.mp
baseurl:          /

twitter:
  username: DiscoStarslayer
  card: summary

author:
  name:           'Darren Thompson'
  url:            https://twitter.com/DiscoStarslayer

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DiscoStarslayer/blog

social:
  name: DiscoStarslayer

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - pygments.rb
  - redcarpet
